/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SSVP;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import SSVP.Cad_info;
import javax.swing.JOptionPane;

/**
 *
 * @author ARAUTO
 */
public class Main extends javax.swing.JFrame {

    Connection conexao2 = Cad_info.conect();
    PreparedStatement pst = null; //Vai aceitar os códigos de SQL dentro do java
    ResultSet rs = null;

    public void CadastroComanda_sql() {
        //Aqui ele irá fazer o comando ao mysql
        String sql = "insert into main values (?,?,?,?,?,?,?)";

        try {
            //as linhas a seguir preparam a consulta ao BD para o login
            // o ? será substituido pelo que for escrito nos campos de texto de login e senha
            pst = conexao2.prepareStatement(sql);
            pst.setString(1, TextNumPedido.getText());
            pst.setString(2, TextVendedor.getText());
            //Estrutura de decisão tamanho
            if (txtPizzaG.isSelected()) {
                pst.setString(3, txtPizzaG.getActionCommand());
            }
            if (txtPizzaM.isSelected()) {
                pst.setString(3, txtPizzaM.getActionCommand());
            }
            if (txtPizzaP.isSelected()) {
                pst.setString(3, txtPizzaP.getActionCommand());
            }
            //Estrutura de decisão de recheio
            if (CheckQueijo.isSelected()) {
                pst.setString(4, CheckQueijo.getText());
            }
            if (CheckCalabresa.isSelected()) {
                pst.setString(4, CheckCalabresa.getText());
            }
            if (CheckBacon.isSelected()) {
                pst.setString(4, CheckBacon.getText());
            }
            pst.setString(5, TextQuantidade.getText());
            //Adiciona data e hora padrão ao mysql
            Date data = new Date();
            SimpleDateFormat formatar = new SimpleDateFormat("YYYY-MM-dd hh:mm:ss");
            String dataFormatada = formatar.format(data);
            pst.setString(6, dataFormatada);
            //Estrutura de decisão pra o delivery
            if (txtEntrega.isSelected()) {
                pst.setString(7, txtEntrega.getText());
            }
            if (txtLocal.isSelected()) {
                pst.setString(7, txtLocal.getText());
            }
            //A seguir iremos consultar a Query do SQL
            pst.executeUpdate();

        } catch (SQLException e) { //Exibe o erro "posso por apenas o e que informa detalhadamente"
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * Creates new form PosLogin
     */
    public Main() {
        initComponents();
    }
    //preços de pizza
    float calabresa = 10;
    float quatroQueijos = 15;
    float bacon = 20;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pedido_label = new javax.swing.JLabel();
        vendedor_label = new javax.swing.JLabel();
        quantidade_label = new javax.swing.JLabel();
        TextVendedor = new javax.swing.JTextField();
        TextNumPedido = new javax.swing.JTextField();
        txtPizzaG = new javax.swing.JRadioButton();
        txtPizzaM = new javax.swing.JRadioButton();
        txtPizzaP = new javax.swing.JRadioButton();
        CheckCalabresa = new javax.swing.JCheckBox();
        CheckQueijo = new javax.swing.JCheckBox();
        CheckBacon = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pedido_label3 = new javax.swing.JLabel();
        TextPrecoPizza = new javax.swing.JTextField();
        TextPrecoRecheio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextPrecoTotal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        TextQuantidade = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JRadioButton();
        txtLocal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE SELEÇÃO DE VENDA DE PIZZAS");
        setPreferredSize(new java.awt.Dimension(1001, 804));

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));
        jPanel1.setName("SSVP"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1001, 725));

        pedido_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pedido_label.setForeground(new java.awt.Color(255, 255, 255));
        pedido_label.setText("Nº PEDIDO");

        vendedor_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vendedor_label.setForeground(new java.awt.Color(255, 255, 255));
        vendedor_label.setText("ATENDENTE");

        quantidade_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quantidade_label.setForeground(new java.awt.Color(255, 255, 255));
        quantidade_label.setText("QUANTIDADE");

        TextNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNumPedidoActionPerformed(evt);
            }
        });
        TextNumPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNumPedidoKeyTyped(evt);
            }
        });

        txtPizzaG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPizzaG.setForeground(new java.awt.Color(255, 255, 255));
        txtPizzaG.setText("G");
        txtPizzaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizzaGActionPerformed(evt);
            }
        });

        txtPizzaM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPizzaM.setForeground(new java.awt.Color(255, 255, 255));
        txtPizzaM.setText("M");
        txtPizzaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizzaMActionPerformed(evt);
            }
        });

        txtPizzaP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPizzaP.setForeground(new java.awt.Color(255, 255, 255));
        txtPizzaP.setText("P");

        CheckCalabresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckCalabresa.setForeground(new java.awt.Color(255, 255, 255));
        CheckCalabresa.setText("CALABRESA");

        CheckQueijo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckQueijo.setForeground(new java.awt.Color(255, 255, 255));
        CheckQueijo.setText("4.QUEIJOS");
        CheckQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckQueijoActionPerformed(evt);
            }
        });

        CheckBacon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckBacon.setForeground(new java.awt.Color(255, 255, 255));
        CheckBacon.setText("BACON");
        CheckBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBaconActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RECHEIOS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VALOR DA MASSA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VALOR TOTAL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VALOR RECHEIO");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Gerar Comanda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Limpar Dados");
        jButton3.setActionCommand("JButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        pedido_label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pedido_label3.setForeground(new java.awt.Color(255, 255, 255));
        pedido_label3.setText("TAMANHO DE PIZZA");

        TextPrecoPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoPizzaActionPerformed(evt);
            }
        });
        TextPrecoPizza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextPrecoPizzaKeyTyped(evt);
            }
        });

        TextPrecoRecheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoRecheioActionPerformed(evt);
            }
        });
        TextPrecoRecheio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextPrecoRecheioKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("8 Fatias");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("6 Fatias");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("4 Fatias");

        TextPrecoTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TextPrecoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoTotalActionPerformed(evt);
            }
        });
        TextPrecoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextPrecoTotalKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*Este campo se auto-preenche");

        TextQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TextQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQuantidadeActionPerformed(evt);
            }
        });
        TextQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextQuantidadeKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("OBS* TAXA DE ENTREGA R$7.00");

        txtEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEntrega.setForeground(new java.awt.Color(255, 255, 255));
        txtEntrega.setText("ENTREGA");
        txtEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntregaActionPerformed(evt);
            }
        });

        txtLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));
        txtLocal.setText("LOCAL");
        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(quantidade_label, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(95, 95, 95))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendedor_label, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pedido_label, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(TextVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButton2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLocal))
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pedido_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtPizzaG)
                                                        .addComponent(txtPizzaP)
                                                        .addComponent(txtPizzaM))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel3))))
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CheckQueijo)
                                                .addComponent(CheckBacon)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CheckCalabresa))
                                            .addGap(51, 51, 51)
                                            .addComponent(TextPrecoRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextPrecoPizza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel7)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jButton3))
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(57, 57, 57)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtEntrega)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel5))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextPrecoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextPrecoRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckCalabresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckQueijo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBacon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextPrecoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pedido_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vendedor_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPizzaG)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pedido_label3)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPizzaM)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPizzaP)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade_label)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrega)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addComponent(txtLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1028, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNumPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNumPedidoActionPerformed

    private void txtPizzaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizzaGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizzaGActionPerformed

    private void txtPizzaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizzaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizzaMActionPerformed

    private void CheckQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckQueijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckQueijoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //Adicionando Data e HORA
        Date data = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM  H:mm");
        String dataFormatada = formatar.format(data);

        //Adicionando todos os campos para resultado;
        int cod_produto = Integer.parseInt(
                TextNumPedido.getText());
        String vendedor = (TextVendedor.getText());
        int quant = Integer.parseInt(TextQuantidade.getText());

        double taxa = 0;

        if (txtPizzaG.isSelected()) {//pizza grande
            taxa = 30;
        } else if (txtPizzaM.isSelected()) {//pizza média
            taxa = 20;
        } else if (txtPizzaP.isSelected()) {//pizza pequena
            taxa = 10;
        }
        //tela de taxa da pizza selecionada;
        TextPrecoPizza.setText(
                "" + taxa);

        double retirada = 0;

        //Condições para os tipos de coberturas;
        if (CheckCalabresa.isSelected()) { //Calabresa
            retirada = calabresa;
            /*if (CheckQueijo.isSelected()){    Para seleção de 2 recheios
                retirada = retirada + calabresa/2;
            } */
        }
        if (CheckQueijo.isSelected()) { //4Queijos
            retirada = quatroQueijos;
            /* if(CheckBacon.isSelected()){
                retirada = retirada + (bacon - 10);
            }*/
        }
        if (CheckBacon.isSelected()) { //Bacon
            retirada = bacon;
        }
        TextPrecoRecheio.setText("" + retirada);

        double taxaDelivery = 7;

        //Total calculado;
        double total_pagar = (taxa * quant) + retirada;

        //Adicionando ao arquivo .txt
        Cad_info cad_info = new Cad_info();
        //Textos
        cad_info.setNum_pedido(TextNumPedido.getText());
        cad_info.setVendedor(TextVendedor.getText());
        cad_info.setQuant(TextQuantidade.getText());
        cad_info.setData_pedido(dataFormatada);
        
        //Delivery
        if (txtEntrega.isSelected()) {
            total_pagar = total_pagar + taxaDelivery;
            cad_info.setDelivery(txtEntrega.getText());
            TextPrecoTotal.setText("" + total_pagar);

        } else {
            cad_info.setDelivery(txtLocal.getText());
            TextPrecoTotal.setText("" + total_pagar);
        }

        cad_info.setPreco_total(TextPrecoTotal.getText());

        //Tela com mais detalhes>>
        jTextArea1.setText("Olá, aqui está o ID do seu pedido: " + cod_produto
                + "\n=========================================================="
                + "\nVendedor: " + vendedor
                + "\t\t Data e Hora: " + dataFormatada
                + "\n=========================================================="
                + "\n MAIS INFORMAÇÕES NA COMANDA IMPRESSA"
                + "\n=========================================================="
                + "\nTotal: " + total_pagar);

        if (txtPizzaG.isSelected()) {
            cad_info.setTam_pizza(txtPizzaG.getActionCommand());
        }
        if (txtPizzaM.isSelected()) {
            cad_info.setTam_pizza(txtPizzaM.getActionCommand());
        }
        if (txtPizzaP.isSelected()) {
            cad_info.setTam_pizza(txtPizzaP.getActionCommand());
        }

        //Recheios
        if (CheckCalabresa.isSelected()) {
            cad_info.setRecheio_pizza(CheckCalabresa.getText());
        }
        if (CheckQueijo.isSelected()) {
            cad_info.setRecheio_pizza(CheckQueijo.getText());
        }
        if (CheckBacon.isSelected()) {
            cad_info.setRecheio_pizza(CheckBacon.getText());
        }
        JOptionPane.showMessageDialog(null, cad_info.Salvar());

        CadastroComanda_sql();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TextNumPedido.setText("");
        TextPrecoPizza.setText("");
        TextVendedor.setText("");
        TextPrecoTotal.setText("");
        TextPrecoRecheio.setText("");
        TextQuantidade.setText("");

        txtPizzaG.setSelected(false);
        txtPizzaM.setSelected(false);
        txtPizzaP.setSelected(false);
        CheckCalabresa.setSelected(false);
        CheckQueijo.setSelected(false);
        CheckBacon.setSelected(false);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TextPrecoRecheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoRecheioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoRecheioActionPerformed

    private void TextPrecoPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoPizzaActionPerformed

    private void CheckBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBaconActionPerformed

    private void TextNumPedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNumPedidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();      //Limita o campo para só exibir/inserir números;
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextNumPedidoKeyTyped

    private void TextPrecoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoTotalActionPerformed

    private void TextPrecoPizzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPrecoPizzaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextPrecoPizzaKeyTyped

    private void TextPrecoRecheioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPrecoRecheioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextPrecoRecheioKeyTyped

    private void TextPrecoTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPrecoTotalKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextPrecoTotalKeyTyped

    private void TextQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQuantidadeActionPerformed

    private void TextQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextQuantidadeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();      //Limita o campo para só exibir/inserir números;
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TextQuantidadeKeyTyped

    private void txtEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntregaActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBacon;
    private javax.swing.JCheckBox CheckCalabresa;
    private javax.swing.JCheckBox CheckQueijo;
    private javax.swing.JTextField TextNumPedido;
    private javax.swing.JTextField TextPrecoPizza;
    private javax.swing.JTextField TextPrecoRecheio;
    private javax.swing.JFormattedTextField TextPrecoTotal;
    private javax.swing.JFormattedTextField TextQuantidade;
    private javax.swing.JTextField TextVendedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel pedido_label;
    private javax.swing.JLabel pedido_label3;
    private javax.swing.JLabel quantidade_label;
    private javax.swing.JRadioButton txtEntrega;
    private javax.swing.JRadioButton txtLocal;
    private javax.swing.JRadioButton txtPizzaG;
    private javax.swing.JRadioButton txtPizzaM;
    private javax.swing.JRadioButton txtPizzaP;
    private javax.swing.JLabel vendedor_label;
    // End of variables declaration//GEN-END:variables

}
